export default [
  // -----------------------------------------------------------------------
  // valid events: https://docs.medusajs.com/v2/resources/events-reference
  // -----------------------------------------------------------------------
  "order.placed",
  "order.canceled",
  "order.completed",
  "auth.password_reset",
  "customer.created",
  //"customer.updated",
  "invite.accepted",
  "invite.created",
  //"invite.deleted",
  "invite.resent",
  "user.created",
  //"user.updated",
  //"user.deleted",

  // -----------------------------------------
  // legacy event types:
  // -----------------------------------------
  // 'batch.created',
  // 'batch.updated',
  // 'batch.canceled',
  // 'batch.pre_processed',
  // 'batch.confirmed',
  // 'batch.processing',
  // 'batch.completed',
  // 'batch.failed',
  // 'claim.created',
  // 'claim.updated',
  // 'claim.canceled',
  // 'claim.fulfillment_created',
  // 'claim.shipment_created',
  // 'claim.refund_processed',
  // 'gift_card.created',
  // 'order.updated',
  // 'order.orders_claimed',
  // 'order.gift_card_created',
  // 'order.payment_captured',
  // 'order.payment_capture_failed',
  // 'order.fulfillment_created',
  // 'order.shipment_created',
  // 'order.fulfillment_canceled',
  // 'order.return_requested',
  // 'order.items_returned',
  // 'order.return_action_required',
  // 'order.refund_created',
  // 'order.refund_failed',
  // 'order.swap_created',
  // 'restock-notification.restocked',
  // 'swap.created',
  // 'swap.received',
  // 'swap.fulfillment_created',
  // 'swap.shipment_created',
  // 'swap.payment_completed',
  // 'swap.payment_captured',
  // 'swap.payment_capture_failed',
  // 'swap.refund_processed',
  // 'swap.process_refund_failed',
];
